<?php
/**
 * Copyright © Banca Transilvania. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

/** @var \BTRL\Ipay\Block\Info\Ipay $block */
/** @var \Magento\Framework\Escaper $escaper */

/** @var \Magento\Sales\Model\Order\Payment $paymentInfo */
$paymentInfo = $block->getInfo();
/** @var \Magento\Sales\Model\Order $order */
$order = $paymentInfo->getOrder();

$creditTotal = $block->getMagentoCreditedAmount($order);
$creditTotalOnline = $block->getOnlineCreditedAmount();
?>
<span><?= $escaper->escapeHtml($block->getMethod()->getTitle()); ?></span>

<table class="data-table admin__table-secondary">
    <tbody>
        <?php if ($btOrderId = $paymentInfo->getAdditionalInformation('orderId')): ?>
            <tr>
                <th><?= __('BT Order ID'); ?></th>
                <td><?= $escaper->escapeHtml($btOrderId); ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($btPaymentStatus = $block->getPaymentStatus()): ?>
            <tr>
                <th><?= __('BT Status'); ?></th>
                <td><?= $escaper->escapeHtml($btPaymentStatus); ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($loyaltyBtOrderId = $block->getLoyaltyOrderNumber()): ?>
            <tr>
                <th><?= __('LOY BT Order ID'); ?></th>
                <td><?= $escaper->escapeHtml($loyaltyBtOrderId); ?></td>
            </tr>
            <?php if ($btPaymentStatus = $block->getPaymentStatus(true)): ?>
                <tr>
                    <th><?= __('LOY BT Status'); ?></th>
                    <td><?= $escaper->escapeHtml($btPaymentStatus); ?></td>
                </tr>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($loyaltyAmount = $block->getLoyaltyAmount()): ?>
            <tr>
                <th><?= __('LOY Paid Amount'); ?></th>
                <td><?= /* @noEscape */ $loyaltyAmount; ?></td>
            </tr>
        <?php endif; ?>

        <?php if (
            $order->getState() === \Magento\Sales\Model\Order::STATE_NEW
            && !empty($paymentInfo->getAdditionalInformation('redirectUrl'))
        ): ?>
            <tr>
                <th><?= __('Payment Link'); ?></th>
                <td>
                    <a rel=noopener
                       target="_blank"
                       href="<?= $escaper->escapeHtml($paymentInfo->getAdditionalInformation('redirectUrl')); ?>"
                    ><?= $escaper->escapeHtml(__('Payment Link')) ?></a>
                </td>
            </tr>
        <?php endif; ?>

        <?php if ($creditTotal !== $creditTotalOnline): ?>
            <tr>
                <th><?= __('Miss-matched refunded amount!'); ?></th>
                <td>
                    <div>
                        <?= $escaper->escapeHtml(
                            __('%1 are refunded in Magento',
                                $block->formatCurrency($order, $creditTotal/100)
                            )
                        ) ?>
                    </div>
                    <div>
                        <?= $escaper->escapeHtml(
                            __('%1 are refunded online',
                                $block->formatCurrency($order, $creditTotalOnline/100)
                            )
                        ) ?>
                    </div>
                </td>
            </tr>
        <?php endif; ?>

        <tr>
            <th><?= __('Update Payment Status'); ?></th>
            <td>
                <a href="<?= $escaper->escapeUrl($block->getUrl('btrl/action/fetchOrderStatus',
                    [
                        'order_id' => $order->getEntityId(),
                        'increment_id' => $order->getIncrementId()
                    ]
                )) ?>">
                    <?= __('Fetch Status'); ?>
                </a>
                <div>
                    <?= __('The payment-status will be updated automatically by default, but in case of any interruption you can use this action to fetch the payment status manually.'); ?>
                </div>
            </td>
        </tr>
    </tbody>
</table>

<?= $escaper->escapeHtml($block->getChildHtml()); ?>
